const allSemesters = [
  {
    id: 1,
    name: "Fall 2020",
    courses: [
      {
        id: 1,
        name: "Mathematics",
        students: [
          { id: 1, fullName: "John Doe", pass: true },
          { id: 2, fullName: "Emily Davis", pass: false },
          { id: 3, fullName: "Michael Johnson", pass: true },
          { id: 4, fullName: "Sarah Brown", pass: true },
          { id: 5, fullName: "David Wilson", pass: false },
          { id: 6, fullName: "Emma Thompson", pass: true },
          { id: 7, fullName: "Daniel Martinez", pass: false },
          { id: 8, fullName: "Olivia Garcia", pass: true },
          { id: 9, fullName: "Jacob Anderson", pass: true },
          { id: 10, fullName: "Sophia Hill", pass: false },
        ],
      },
      {
        id: 2,
        name: "Physics",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
     
        ],
      },
      {
        id: 3,
        name: "English",
        students: [
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Henry",
          "Abigail",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 4,
        name: "Chemistry",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 5,
        name: "Biology",
        students: [
          "Daniel",
          "Emily",
          "Jacob",
          "Mia",
          "Benjamin",
          "Amelia",
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
        ],
      },
      {
        id: 6,
        name: "Art",
        students: [
          "Olivia",
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
        ],
      },
      {
        id: 7,
        name: "Psychology",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 8,
        name: "Computer Science",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 9,
        name: "History",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 10,
        name: "Geography",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Spring 2021",
    courses: [
      {
        id: 11,
        name: "Sociology",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 12,
        name: "Economics",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 13,
        name: "Spanish",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 14,
        name: "Literature",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 15,
        name: "Statistics",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 16,
        name: "Physical Education",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 17,
        name: "Geography",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 18,
        name: "Music",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 19,
        name: "Political Science",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 20,
        name: "Anthropology",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Fall 2021",
    courses: [
      {
        id: 21,
        name: "Philosophy",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 22,
        name: "Theater",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 23,
        name: "Environmental Science",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 24,
        name: "Marketing",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 25,
        name: "French",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 26,
        name: "Engineering",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 27,
        name: "Communications",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 28,
        name: "Japanese",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 29,
        name: "Psychiatry",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 30,
        name: "Business Management",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Spring 2022",
    courses: [
      {
        id: 31,
        name: "Chemical Engineering",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 32,
        name: "Sociology",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 33,
        name: "Latin",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 34,
        name: "Astronomy",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 35,
        name: "Finance",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 36,
        name: "Italian",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 37,
        name: "Human Resources",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 38,
        name: "Criminal Justice",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 39,
        name: "Russian",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 40,
        name: "Geology",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Fall 2022",
    courses: [
      {
        id: 41,
        name: "Digital Media",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 42,
        name: "Ethics",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 43,
        name: "Chinese",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 44,
        name: "Journalism",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 45,
        name: "Public Speaking",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 46,
        name: "Swedish",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 47,
        name: "Social Work",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 48,
        name: "Linguistics",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 49,
        name: "Portuguese",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 50,
        name: "Architecture",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Spring 2023",
    courses: [
      {
        id: 51,
        name: "International Relations",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 52,
        name: "Hindi",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 53,
        name: "Neuroscience",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 54,
        name: "Fashion Design",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 55,
        name: "Arabic",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 56,
        name: "Astrophysics",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
      {
        id: 57,
        name: "Education",
        students: [
          "Michael",
          "Charlotte",
          "David",
          "Sophia",
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
        ],
      },
      {
        id: 58,
        name: "German",
        students: [
          "Jacob",
          "Sophia",
          "Liam",
          "Harper",
          "Alexander",
          "Evelyn",
          "Daniel",
          "Emily",
          "Michael",
          "Sarah",
        ],
      },
      {
        id: 59,
        name: "Medical Science",
        students: [
          "Ethan",
          "Isabella",
          "Matthew",
          "Ava",
          "William",
          "Mia",
          "James",
          "Charlotte",
          "Benjamin",
          "Amelia",
        ],
      },
      {
        id: 60,
        name: "Theology",
        students: [
          "Andrew",
          "Olivia",
          "Christopher",
          "Emma",
          "Nicholas",
          "Ava",
          "Daniel",
          "Emily",
          "Joseph",
          "Elizabeth",
        ],
      },
    ],
  },
  // Continue adding more semesters...
];

export default allSemesters;
